import './globals.css';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'COS project',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="flex flex-column justify-center">
      <body>{children}</body>
    </html>
  );
}
