'use client';

import './globals.css';

import { RecoilRoot } from 'recoil';

import ClientOnlyRecoil from '@/components/common/ClientOnlyRecoil';
import Timer from '@/components/common/Timer';
import { certificateNameAtom } from '@/recoil/atom';

// export const metadata: Metadata = {
//   title: 'COS project',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="">
      <body>
        <ClientOnlyRecoil>{children}</ClientOnlyRecoil>
      </body>
    </html>
  );
}
